name: Staging Build

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  staging-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: ugh
        run: npm i -g yarn

      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install Packages
        run: yarn

      - name: Build
        run: yarn build:staging

      - name: Deploy to staging via rsync
        uses: burnett01/rsync-deployments@4.1
        with:
          switches: -avzr --delete
          path: build/
          remote_path: /home/staging/imcore.react/
          remote_host: ${{ secrets.SSH_HOST }}
          remote_port: ${{ secrets.SSH_PORT }}
          remote_user: ${{ secrets.SSH_USERNAME }}
          remote_key: ${{ secrets.SSH_KEY }}